/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dynamic_subjtable;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import net.sf.dynamicreports.report.constant.PageOrientation;
import net.sf.dynamicreports.report.constant.PageType;
import net.sf.dynamicreports.report.exception.DRException;
import raven.dynamicjasper.template.PageFormat;
import test.PageConfigDialog;

/**
 *
 * @author RAVEN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private PageFormat pageFormat = new PageFormat(PageType.A4, 0, 0, PageOrientation.PORTRAIT);

    public Main() {
        initComponents();
        //  Test Data
        init();
    }

    private void init() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addRow(new Object[]{1, "John", "$ 150", getSubTableData()});
        model.addRow(new Object[]{2, "Tomash", "$ 200", getSubTableData()});
        //model.addRow(new Object[]{3, "Dara", "$ 130", getSubTableData()});
        //model.addRow(new Object[]{4, "Bo", "$ 520", getSubTableData()});
        table.autoRowHeight(table);
    }

    public DefaultTableModel getSubTableData() {
        DefaultTableModel data = new DefaultTableModel();
        data.setColumnCount(4);
        data.addRow(new Object[]{new Header("No", 10), new Header("Item"), new Header("Total", 200), new Header("Detail", 200)});
        data.addRow(new Object[]{"1", "ABC", "$ 50", getSubTableData1()});
        data.addRow(new Object[]{"2", "Vital", "$ 70", getSubTableData1()});
        // data.addRow(new Object[]{"3", "Fanta", "$ 20", getSubTableData1()});
        // data.addRow(new Object[]{"4", "Coca", "$ 35", getSubTableData1()});
        return data;
    }

    public DefaultTableModel getSubTableData1() {
        DefaultTableModel data = new DefaultTableModel();
        data.setColumnCount(3);
        data.addRow(new Object[]{new Header("No", 10), new Header("Type"), new Header("Qty")});
        data.addRow(new Object[]{1, "Unit", "50"});
        data.addRow(new Object[]{1, "Case", "70"});
        data.addRow(new Object[]{1, "Box", "3"});
        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new dynamic_subjtable.TableCustom();
        cmdPrint = new javax.swing.JButton();
        cmdSetupPage = new javax.swing.JButton();
        cmdPrint1 = new javax.swing.JButton();
        cmdPrint3 = new javax.swing.JButton();
        cmdPrint4 = new javax.swing.JButton();
        cmdPrint2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Customer", "Amount", "Product List"
            }
        ));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(3).setPreferredWidth(500);
        }

        cmdPrint.setText("View");
        cmdPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrintActionPerformed(evt);
            }
        });

        cmdSetupPage.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cmdSetupPage.setText("Setup Page");
        cmdSetupPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSetupPageActionPerformed(evt);
            }
        });

        cmdPrint1.setText("Print to Excel");
        cmdPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrint1ActionPerformed(evt);
            }
        });

        cmdPrint3.setText("Print to Word");
        cmdPrint3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrint3ActionPerformed(evt);
            }
        });

        cmdPrint4.setText("Print to Pdf");
        cmdPrint4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrint4ActionPerformed(evt);
            }
        });

        cmdPrint2.setText("Print To Image");
        cmdPrint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrint2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmdSetupPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdPrint2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdPrint4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdPrint3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdPrint1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdPrint1)
                        .addComponent(cmdPrint2)
                        .addComponent(cmdPrint3)
                        .addComponent(cmdPrint4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdPrint)
                        .addComponent(cmdSetupPage)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private ReportOption getReportOption() {
        return new ReportOption("", "No", "Customer", "Amount", new ReportOption("Product List", "No", "Item", "Total", new ReportOption("Detail", "No", "Type", "Qty")));
    }

    private void cmdPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrintActionPerformed
        try {
            new PrintTableDetails().printTable(table.getModel(), "Dynamic Jasper Report Java", pageFormat, getReportOption()).view();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmdPrintActionPerformed

    private void cmdSetupPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSetupPageActionPerformed
        PageConfigDialog dia = new PageConfigDialog(this, true);
        dia.setPageFormat(pageFormat);
        dia.setVisible(true);
        if (dia.getPageFormat() != null) {
            pageFormat = dia.getPageFormat();
        }
    }//GEN-LAST:event_cmdSetupPageActionPerformed

    private void cmdPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrint1ActionPerformed
        File file = showFileChooser();
        if (file != null) {
            try {
                File f = new PrintTableDetails().printTable(table.getModel(), "Test Report", pageFormat, getReportOption()).exportToExcel(file);
                Desktop.getDesktop().open(f);
            } catch (IOException | DRException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmdPrint1ActionPerformed

    private void cmdPrint3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrint3ActionPerformed
        File file = showFileChooser();
        if (file != null) {
            try {
                File f = new PrintTableDetails().printTable(table.getModel(), "Test Report", pageFormat, getReportOption()).exportToWord(file);
                Desktop.getDesktop().open(f);
            } catch (IOException | DRException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmdPrint3ActionPerformed

    private void cmdPrint4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrint4ActionPerformed
        File file = showFileChooser();
        if (file != null) {
            try {
                File f = new PrintTableDetails().printTable(table.getModel(), "Test Report", pageFormat, getReportOption()).exportToPdf(file);
                Desktop.getDesktop().open(f);
            } catch (IOException | DRException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmdPrint4ActionPerformed

    private void cmdPrint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrint2ActionPerformed
        File file = showFileChooser();
        if (file != null) {
            try {
                File f = new PrintTableDetails().printTable(table.getModel(), "Test Report", pageFormat, getReportOption()).exportToImage(file);
                Desktop.getDesktop().open(f);
            } catch (IOException | DRException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmdPrint2ActionPerformed

    private File showFileChooser() {
        JFileChooser ch = new JFileChooser();
        int opt = ch.showSaveDialog(this);
        if (opt == JFileChooser.APPROVE_OPTION) {
            return ch.getSelectedFile();
        } else {
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdPrint;
    private javax.swing.JButton cmdPrint1;
    private javax.swing.JButton cmdPrint2;
    private javax.swing.JButton cmdPrint3;
    private javax.swing.JButton cmdPrint4;
    private javax.swing.JButton cmdSetupPage;
    private javax.swing.JScrollPane jScrollPane1;
    private dynamic_subjtable.TableCustom table;
    // End of variables declaration//GEN-END:variables
}
