package test;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.dynamicreports.report.constant.PageOrientation;
import net.sf.dynamicreports.report.constant.PageType;
import net.sf.dynamicreports.report.exception.DRException;
import raven.dynamicjasper.template.PageFormat;

/**
 *
 * @author RAVEN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private PageFormat pageFormat = new PageFormat(PageType.A4, 0, 0, PageOrientation.PORTRAIT);

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        cmdPrint = new javax.swing.JButton();
        cmdPrint1 = new javax.swing.JButton();
        cmdPrint2 = new javax.swing.JButton();
        cmdPrint3 = new javax.swing.JButton();
        cmdPrint4 = new javax.swing.JButton();
        cmdSetupPage = new javax.swing.JButton();
        cmdAddColumn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "dara", "10", "dfdf"},
                {"2", "raven", "20", "fhfhjjj4545ff"},
                {"3", "A", "30", "ioioiljkkk"},
                {"4", "B", "40", null}
            },
            new String [] {
                "No", "Name", "Age", "Description"
            }
        ));
        jScrollPane1.setViewportView(table);

        cmdPrint.setText("View");
        cmdPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrintActionPerformed(evt);
            }
        });

        cmdPrint1.setText("Print to Excel");
        cmdPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrint1ActionPerformed(evt);
            }
        });

        cmdPrint2.setText("Print To Image");
        cmdPrint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrint2ActionPerformed(evt);
            }
        });

        cmdPrint3.setText("Print to Word");
        cmdPrint3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrint3ActionPerformed(evt);
            }
        });

        cmdPrint4.setText("Print to Pdf");
        cmdPrint4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrint4ActionPerformed(evt);
            }
        });

        cmdSetupPage.setText("Setup Page");
        cmdSetupPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSetupPageActionPerformed(evt);
            }
        });

        cmdAddColumn.setText("Add Column");
        cmdAddColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddColumnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdSetupPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                        .addComponent(cmdPrint2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdPrint4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdPrint3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdPrint1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmdAddColumn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdAddColumn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdPrint)
                    .addComponent(cmdPrint1)
                    .addComponent(cmdPrint2)
                    .addComponent(cmdPrint3)
                    .addComponent(cmdPrint4)
                    .addComponent(cmdSetupPage))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrintActionPerformed
        try {
            new PrintTable().printTable(table.getModel(), "Dynamic Report", pageFormat);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmdPrintActionPerformed

    private void cmdPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrint1ActionPerformed
        File file = showFileChooser();
        if (file != null) {
            try {
                File f = new PrintTable().printTable(table.getModel(), "Test Report", pageFormat).exportToExcel(file);
                Desktop.getDesktop().open(f);
            } catch (IOException | DRException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmdPrint1ActionPerformed

    private void cmdPrint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrint2ActionPerformed
        File file = showFileChooser();
        if (file != null) {
            try {
                File f = new PrintTable().printTable(table.getModel(), "Test Report", pageFormat).exportToImage(file);
                Desktop.getDesktop().open(f);
            } catch (IOException | DRException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmdPrint2ActionPerformed

    private void cmdPrint3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrint3ActionPerformed
        File file = showFileChooser();
        if (file != null) {
            try {
                File f = new PrintTable().printTable(table.getModel(), "Test Report", pageFormat).exportToWord(file);
                Desktop.getDesktop().open(f);
            } catch (IOException | DRException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmdPrint3ActionPerformed

    private void cmdPrint4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrint4ActionPerformed
        File file = showFileChooser();
        if (file != null) {
            try {
                File f = new PrintTable().printTable(table.getModel(), "Test Report", pageFormat).exportToPdf(file);
                Desktop.getDesktop().open(f);
            } catch (IOException | DRException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmdPrint4ActionPerformed

    private void cmdSetupPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSetupPageActionPerformed
        PageConfigDialog dia = new PageConfigDialog(this, true);
        dia.setPageFormat(pageFormat);
        dia.setVisible(true);
        if (dia.getPageFormat() != null) {
            pageFormat = dia.getPageFormat();
        }
    }//GEN-LAST:event_cmdSetupPageActionPerformed

    private void cmdAddColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddColumnActionPerformed
        String name = JOptionPane.showInputDialog(this, "Column Name");
        if (name != null) {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.addColumn(name);
        }
    }//GEN-LAST:event_cmdAddColumnActionPerformed

    private File showFileChooser() {
        JFileChooser ch = new JFileChooser();
        int opt = ch.showSaveDialog(this);
        if (opt == JFileChooser.APPROVE_OPTION) {
            return ch.getSelectedFile();
        } else {
            return null;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAddColumn;
    private javax.swing.JButton cmdPrint;
    private javax.swing.JButton cmdPrint1;
    private javax.swing.JButton cmdPrint2;
    private javax.swing.JButton cmdPrint3;
    private javax.swing.JButton cmdPrint4;
    private javax.swing.JButton cmdSetupPage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
